version: '3'
services:
  app:
    image: golang:1.21-alpine
    container_name: anime_service
    volumes:
      - .:/usr/src/app:ro
    working_dir: /usr/src/app
    command: go run ./cmd/app
    environment:
      NLP_BASE_URL: http://nlp:8085/
    ports:
      - "8080:8080"
  nlp:
    build: nlp
    container_name: nlp
    restart: unless-stopped
    environment:
      HOST: "0.0.0.0"
      PORT: 8085
    ports:
      - "8085:8085"
